"""
doc_export.py — DOCX export helper for Code Sentinel documentation agent output.

Converts the documentation agent's JSON dict into a properly formatted
Microsoft Word (.docx) file and returns the raw bytes.
"""
import json
from datetime import datetime, timezone
from io import BytesIO

from docx import Document
from docx.shared import Pt, RGBColor


def build_docx(doc_data: dict, job_name: str) -> bytes:
    """
    Convert a documentation agent result dict into a .docx file.

    Returns the file bytes (suitable for st.download_button or S3 upload).
    """
    doc = Document()

    # ---- Title ----
    doc.add_heading(f"{job_name} — Documentation" if job_name else "Documentation", 0)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sub = doc.add_paragraph(f"Generated by Code Sentinel · {ts}")
    sub.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    sub.runs[0].font.size = Pt(9)

    # ---- Overview ----
    doc.add_heading("Overview", 1)
    doc.add_paragraph(doc_data.get("business_summary", ""))

    # ---- Inputs ----
    doc.add_heading("Inputs", 1)
    inputs = doc_data.get("inputs") or []
    if inputs:
        for item in inputs:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"{item.get('source', '—')}: ")
            run.bold = True
            p.add_run(item.get("description", ""))
    else:
        doc.add_paragraph("No inputs documented.")

    # ---- Outputs ----
    doc.add_heading("Outputs", 1)
    outputs = doc_data.get("outputs") or []
    if outputs:
        for item in outputs:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"{item.get('destination', '—')}: ")
            run.bold = True
            p.add_run(item.get("description", ""))
    else:
        doc.add_paragraph("No outputs documented.")

    # ---- Transformation Logic ----
    doc.add_heading("Transformation Logic", 1)
    for i, step in enumerate(doc_data.get("transformation_logic") or [], 1):
        doc.add_paragraph(f"{i}. {step}")

    # ---- Operational Notes ----
    doc.add_heading("Operational Notes", 1)
    for note in doc_data.get("operational_notes") or []:
        doc.add_paragraph(note, style="List Bullet")

    # ---- Generated Docstring ----
    raw_ds = doc_data.get("generated_docstring", "")
    if raw_ds:
        doc.add_heading("Generated Docstring", 1)
        p = doc.add_paragraph(raw_ds.replace("\\n", "\n"))
        for run in p.runs:
            run.font.name = "Courier New"
            run.font.size = Pt(9)

    # ---- Footer note ----
    doc.add_paragraph("")
    footer_p = doc.add_paragraph("Code Sentinel · AI-generated documentation")
    footer_p.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    footer_p.runs[0].font.size = Pt(8)
    footer_p.runs[0].italic = True

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_ipynb(code: str, source_filename: str = "optimized.py") -> bytes:
    """
    Wrap a Python code string into a minimal valid .ipynb file with one
    code cell. Returns bytes ready for download.
    """
    notebook = {
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": code.splitlines(keepends=True),
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=2).encode("utf-8")
